Name - saurabh
Roll No - 102383677
Group - 3Co33
ML - Assignment 1




Q1: Questions on Basic NumPy Array





In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
a=np.flip(arr)

print(a)


[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
using any two NumPy in-built methods


In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array1 = array1.flatten()
print("Flattened array using flatten():", flattened_array1)
flattened_array2 = array1.ravel()
print("Flattened array using ravel():", flattened_array2)


Flattened array using flatten(): [1 2 3 2 4 5 1 2 3]
Flattened array using ravel(): [1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:


In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
are_equal = np.array_equal(arr1, arr2)

print("Are the arrays equal?", are_equal)


Are the arrays equal? True


(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [5]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
def most_frequent_value_and_indices(arr):
    counts = np.bincount(arr)
    most_frequent_value = np.argmax(counts)
    indices = np.where(arr == most_frequent_value)[0]

    return most_frequent_value, indices

x_value, x_indices = most_frequent_value_and_indices(x)
print("For array x:")
print("Most frequent value:", x_value)
print("Indices of most frequent value:", x_indices)

y_value, y_indices = most_frequent_value_and_indices(y)
print("For array y:")
print("Most frequent value:", y_value)
print("Indices of most frequent value:", y_indices)


For array x:
Most frequent value: 1
Indices of most frequent value: [0 5 7 8 9]
For array y:
Most frequent value: 1
Indices of most frequent value: [0 1 2]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise


In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sum_all_elements = np.sum(gfg)

sum_row_wise = np.sum(gfg, axis=1)

sum_column_wise = np.sum(gfg, axis=0)

print("Sum of all elements:", sum_all_elements)
print("Sum of all elements row-wise:", sum_row_wise)
print("Sum of all elements column-wise:", sum_column_wise)


Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix


In [7]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

sum_diagonal = np.trace(n_array)
print("Sum of diagonal elements:", sum_diagonal)

eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

inverse_matrix = np.linalg.inv(n_array)
print("Inverse of the matrix:\n", inverse_matrix)

determinant = np.linalg.det(n_array)
print("Determinant of the matrix:", determinant)


Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001



(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]


In [8]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.dot(p1, q1)
print("Part (i) - Matrix multiplication result:\n", product1)

p1_flat = p1.flatten()
q1_flat = q1.flatten()
cov_matrix1 = np.cov(p1_flat, q1_flat)
print("Part (i) - Covariance matrix:\n", cov_matrix1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

product2 = np.dot(p2, q2)
print("Part (ii) - Matrix multiplication result:\n", product2)

p2_flat = p2.flatten()
q2_flat = q2.flatten()
cov_matrix2 = np.cov(p2_flat, q2_flat)
print("Part (ii) - Covariance matrix:\n", cov_matrix2)


Part (i) - Matrix multiplication result:
 [[16 19]
 [26 31]]
Part (i) - Covariance matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Part (ii) - Matrix multiplication result:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Part (ii) - Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?


In [9]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

x_flat = x.flatten()
y_flat = y.flatten()

inner_product = np.dot(x_flat, y_flat)
print("Inner product:", inner_product)

outer_product = np.outer(x_flat, y_flat)
print("Outer product:\n", outer_product)

x_expanded = x_flat[:, np.newaxis]
y_repeated = np.repeat(y_flat, len(x_flat)).reshape(len(x_flat), -1)
cartesian_product = np.concatenate([x_expanded, y_repeated], axis=1)
print("Cartesian product:\n", cartesian_product)


Inner product: 79
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1  1  1  1  1  1]
 [ 3  5  5  5  5  5  5]
 [ 4  0  0  0  0  0  0]
 [ 3  5  5  5  5  5  5]
 [ 2 10 10 10 10 10 10]
 [ 9  3  3  3  3  3  3]]


Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row


In [10]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

absolute_array = np.abs(array)
print("Element-wise absolute value:")
print(absolute_array)

flattened_array = array.flatten()
percentiles_flat = np.percentile(flattened_array, [25, 50, 75])

print("\nPercentiles of flattened array:")
print(f"25th percentile: {percentiles_flat[0]}")
print(f"50th percentile: {percentiles_flat[1]}")
print(f"75th percentile: {percentiles_flat[2]}")

percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
print("\nPercentiles of each column:")
print(f"25th percentile: {percentiles_columns[0]}")
print(f"50th percentile: {percentiles_columns[1]}")
print(f"75th percentile: {percentiles_columns[2]}")

percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("\nPercentiles of each row:")
print(f"25th percentile: {percentiles_rows[0]}")
print(f"50th percentile: {percentiles_rows[1]}")
print(f"75th percentile: {percentiles_rows[2]}")
mean_flat = np.mean(flattened_array)
median_flat = np.median(flattened_array)
std_flat = np.std(flattened_array)

print("\nFlattened array statistics:")
print(f"Mean: {mean_flat}")
print(f"Median: {median_flat}")
print(f"Standard Deviation: {std_flat}")

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

print("\nEach column statistics:")
print(f"Mean: {mean_columns}")
print(f"Median: {median_columns}")
print(f"Standard Deviation: {std_columns}")

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("\nEach row statistics:")
print(f"Mean: {mean_rows}")
print(f"Median: {median_rows}")
print(f"Standard Deviation: {std_rows}")


Element-wise absolute value:
[[1 2 3]
 [4 5 6]]

Percentiles of flattened array:
25th percentile: -3.5
50th percentile: -0.5
75th percentile: 2.5

Percentiles of each column:
25th percentile: [-2.75 -0.25 -3.75]
50th percentile: [-1.5  1.5 -1.5]
75th percentile: [-0.25  3.25  0.75]

Percentiles of each row:
25th percentile: [-0.5 -5. ]
50th percentile: [ 1. -4.]
75th percentile: [2.  0.5]

Flattened array statistics:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Each column statistics:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Each row statistics:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values



In [11]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)
print("Floor values:")
print(floor_values)

ceiling_values = np.ceil(a)
print("\nCeiling values:")
print(ceiling_values)

truncated_values = np.trunc(a)
print("\nTruncated values:")
print(truncated_values)

rounded_values = np.round(a)
print("\nRounded values:")
print(rounded_values)


Floor values:
[-2. -2. -1.  0.  1.  1.  3.]

Ceiling values:
[-1. -1. -0.  1.  2.  2.  3.]

Truncated values:
[-1. -1. -0.  0.  1.  1.  3.]

Rounded values:
[-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements


In [12]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
print("Sorted array:")
print(sorted_array)

indices_of_sorted_array = np.argsort(array)
print("\nIndices of sorted array:")
print(indices_of_sorted_array)

smallest_4_elements = np.partition(array, 4)[:4]
smallest_4_elements_sorted = np.sort(smallest_4_elements)
print("\n4 smallest elements:")
print(smallest_4_elements_sorted)

largest_5_elements = np.partition(array, -5)[-5:]
largest_5_elements_sorted = np.sort(largest_5_elements)
print("\n5 largest elements:")
print(largest_5_elements_sorted)



Sorted array:
[ 10  16  16  52  54  62 453]

Indices of sorted array:
[0 3 4 1 5 2 6]

4 smallest elements:
[10 16 16 52]

5 largest elements:
[ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only


In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_elements = array[array == np.floor(array)]
print("Integer elements only:")
print(integer_elements)

float_elements = array[array != np.floor(array)]
print("\nFloat elements only:")
print(float_elements)


Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)


In [15]:
pip install opencv-python

import cv2
import numpy as np
from google.colab import files

uploaded = files.upload()

def img_to_array(path):

    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)

    if img is None:
        raise FileNotFoundError(f"The image at path {path} could not be found or read.")

    if len(img.shape) == 3:
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        text_file_path = path + "_rgb.txt"
        with open(text_file_path, 'w') as f:
            for row in img_rgb:
                for pixel in row:
                    f.write(' '.join(map(str, pixel)) + ' ')
                f.write('\n')

    elif len(img.shape) == 2:
        text_file_path = path + "_greyscale.txt"
        with open(text_file_path, 'w') as f:
            for row in img:
                f.write(' '.join(map(str, row)) + '\n')
    else:
        raise ValueError("Unsupported image format or image array dimension")

    print(f"Image data saved to {text_file_path}")
    return text_file_path

filename = list(uploaded.keys())[0]

text_file_path = img_to_array(filename)

files.download(text_file_path)


SyntaxError: invalid syntax (<ipython-input-15-4eba9bb2a97d>, line 1)

(b) Load the saved file into jupyter notebook?


In [ ]:
from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

import pandas as pd
import json

try:
    df = pd.read_csv(file_name)
    print("CSV File loaded successfully!")
    print(df.head())
except Exception as e:
    print(f"Error loading CSV file: {e}")

try:
    with open(file_name, 'r') as file:
        text_content = file.read()
    print("\nText File loaded successfully!")
    print(text_content)
except Exception as e:
    print(f"Error loading text file: {e}")

try:
    with open(file_name, 'r') as file:
        json_data = json.load(file)
    print("\nJSON File loaded successfully!")
    print(json_data)
except Exception as e:
    print(f"Error loading JSON file: {e}")